### PR TITLE
Creator Reward Withdrawal Limit

### PR DESCRIPTION
**Pull request by aggre**
This is a DIP for setting a withdrawal limit for creator rewards.

See [the DIP](https://github.com/dev-protocol/DIPs/blob/dip-creator-reward-withdrawal-limit/DIPS/dip-38.md) for details.

### CODE REVIEW

**Comment by aggre** [comment]
I've added a simulation to illustrate how this DIP works on the effective APY of creator rewards:
https://github.com/dev-protocol/DIPs/blob/dip-creator-reward-withdrawal-limit/DIPS/dip-38.md#simulation

**Comment by Akira-Taniguchi** [comment]
genius!

@aggre

**Comment by defi-er** [comment]
What if a creator has multiple properties? Do they receive additional benefits under this proposal?

**Comment by aggre** [comment]
> What if a creator has multiple properties? Do they receive additional benefits under this proposal?

@defi-er If one creator owns many properties, they will be more motivated to self-stake than other creators. This DIP cannot solve it. (I'll add that later)

In my opinion, updating the authentication fee will help. Increasing the number of DEV burned for authentication increases the cost of holding a large amount. However, it is not perfect because it also works for non-malicious creators.

Still, I believe this DIP can solve most of the self-staking problems.

I also hope that a better unknown algorithm will replace it in the future.

**Comment by calaber24p** [comment]
I think this is a clever way to disinecentivize larger creators from self staking. While many smaller creators will still be able to stake on themselves, they have a smaller effect on the market by far. I think this is a great first step in combating self staking. In many ways this will also have a side effect of lowering the effective inflation rate. 

@defi-er makes a good point about those with multiple properties being able to split their coins between them. At the moment we should be more alert of this possibility and take steps to make sure it doesnt happen for future creators. Personally I believe we should force new creators to wrap multiple properties under one staking property, but that would be another discussion entirely and for another time.

**Comment by aggre** [comment]
> What do you think of creating a quadratic staking function that lowers reward when you stake them in one asset?

@defi-er In my understanding, you propose to "lower the creator reward for a Property if a Property holder stakes on their own Property." Is this correct? I want to consider it, so please give me some time. (By the way, as we know, it doesn't work perfectly if the creator has more than one wallet account)

**Comment by defi-er** [comment]
The only full proof solution is to require users to use a decentralized identity tool like BrightID or Proof of Humanity

**Comment by aggre** [comment]
@defi-er I'll add your proposal to this DIP.

I will commit the specification. Simply put, if a Property holder stakes, the creator reward from that staking is canceled, but the staking reward is still earned.

**Comment by aggre** [comment]
I've added that specification: https://github.com/dev-protocol/DIPs/pull/38/commits/35ff87103ab10c5c87fcb92e67ee02f4e86d24e6

Then, in the "Proposed Code" section, I'll add the technical requirements.

**Comment by aggre** [comment]
I've added a section on updating the code:
https://github.com/dev-protocol/DIPs/blob/dip-creator-reward-withdrawal-limit/DIPS/dip-38.md#proposed-code-updating

**Comment by aggre** [comment]
Since computing the geometric mean with on-chain requires many iterations, the geometric mean will be updated periodically (e.g., every hour) by an oracle until an effective computation reduction plan is found.

**Comment by aggre** [comment]
I think we can already advance this DIP into the voting flow.

**Comment by aggre** [comment]
We were found that the specification to "reduce creator rewards when self-staking by the same account" is accompanied by the technical difficulty that "cannot calculate the number of stakings that are eligible for creator rewards."

We are considering two specifications as alternatives:
1. Plan-A: Returns an error if the staking user is also the target Property holder.
2. Plan-B: No change

### Advantages/Disadvantages

Plan-A Advantages
- Self-staking by the same account becomes impossible
- By explicitly returning an error, it can educate users about bad behavior

Plan-A Disadvantages
- Increasing error-conditions hinders composability

Plan-B Advantages
- Not affect composability
- Gas fees are slightly cheaper than Plan-A

Plan-B Disadvantages
- Self-staking by the same account cannot be prevented _(however, self-staking makes the reward increase inefficient by DIP38)_

**Comment by aggre** [comment]
I agree with Plan-B. I think Plan-A may interfere with money-lego and thereby hinder network effects.

**Comment by Akira-Taniguchi** [comment]
me too.

**Pull request merged**
